import { DocLayout } from "@/components/layout/DocLayout";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { InfoBox } from "@/components/docs/InfoBox";
import { SectionHeader } from "@/components/docs/SectionHeader";
import { FileCode, Globe, Server, ArrowRight, Shield } from "lucide-react";

const Architecture = () => {
  return (
    <DocLayout>
      <div className="animate-fade-in">
        <div className="mb-8">
          <h1 className="text-3xl lg:text-4xl font-bold mb-4">
            <span className="gradient-text">Architecture</span>
          </h1>
          <p className="text-lg text-muted-foreground">
            A comprehensive overview of AproxMixer's system architecture, components, 
            and data flow from deposit to withdrawal.
          </p>
        </div>

        {/* Smart Contracts */}
        <SectionHeader 
          title="Smart Contracts" 
          subtitle="On-chain protocol components"
          id="contracts"
        />

        <div className="space-y-4 mb-12">
          <p className="text-muted-foreground">
            The core protocol logic is implemented in Solidity smart contracts deployed on 
            Ethereum-compatible networks. The main contracts are:
          </p>

          <div className="gradient-border rounded-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
                <FileCode className="w-5 h-5 text-primary" />
              </div>
              <h3 className="text-xl font-semibold">Mixer.sol</h3>
            </div>
            <p className="text-muted-foreground mb-4">
              The main mixing contract that handles deposits and withdrawals. It maintains a Merkle tree 
              of commitments and verifies zk-SNARK proofs during withdrawals.
            </p>
            <CodeBlock
              language="solidity"
              code={`contract Mixer {
    IVerifier public verifier;
    MerkleTree public merkleTree;
    
    mapping(bytes32 => bool) public nullifierHashes;
    mapping(bytes32 => bool) public commitments;
    
    uint256 public denomination; // Fixed deposit amount
    
    event Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp);
    event Withdrawal(address to, bytes32 nullifierHash, address relayer, uint256 fee);
    
    function deposit(bytes32 _commitment) external payable {
        require(msg.value == denomination, "Invalid deposit amount");
        require(!commitments[_commitment], "Commitment already exists");
        
        uint32 index = merkleTree.insert(_commitment);
        commitments[_commitment] = true;
        
        emit Deposit(_commitment, index, block.timestamp);
    }
    
    function withdraw(
        bytes calldata _proof,
        bytes32 _root,
        bytes32 _nullifierHash,
        address payable _recipient,
        address payable _relayer,
        uint256 _fee
    ) external {
        require(!nullifierHashes[_nullifierHash], "Note already spent");
        require(merkleTree.isKnownRoot(_root), "Invalid merkle root");
        
        require(verifier.verifyProof(_proof, [
            uint256(_root),
            uint256(_nullifierHash),
            uint256(uint160(_recipient)),
            uint256(uint160(_relayer)),
            _fee
        ]), "Invalid proof");
        
        nullifierHashes[_nullifierHash] = true;
        
        // Transfer funds
        _recipient.transfer(denomination - _fee);
        if (_fee > 0) _relayer.transfer(_fee);
        
        emit Withdrawal(_recipient, _nullifierHash, _relayer, _fee);
    }
}`}
            />
          </div>

          <div className="gradient-border rounded-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-lg bg-secondary/20 flex items-center justify-center">
                <Shield className="w-5 h-5 text-secondary" />
              </div>
              <h3 className="text-xl font-semibold">Verifier.sol</h3>
            </div>
            <p className="text-muted-foreground mb-4">
              Auto-generated contract from the zk-SNARK circuit compilation. Verifies proofs 
              on-chain using the Groth16 proving system.
            </p>
            <CodeBlock
              language="solidity"
              code={`// Generated by snarkjs
contract Verifier {
    // Verification key components
    uint256 constant alphax = ...;
    uint256 constant alphay = ...;
    // ... elliptic curve parameters
    
    function verifyProof(
        bytes memory proof,
        uint256[] memory pubSignals
    ) public view returns (bool) {
        // Pairing check for Groth16 verification
        return Pairing.pairingCheck(...);
    }
}`}
            />
          </div>
        </div>

        {/* Frontend */}
        <SectionHeader 
          title="Frontend Application" 
          subtitle="React + Vite web application"
          id="frontend"
        />

        <div className="space-y-4 mb-12">
          <p className="text-muted-foreground">
            The frontend is built with modern web technologies for optimal performance and developer experience.
          </p>

          <div className="glass-card rounded-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <Globe className="w-5 h-5 text-primary" />
              <h4 className="font-semibold">Technology Stack</h4>
            </div>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-lg bg-muted/30 border border-border/50">
                <h5 className="font-medium mb-2">Core Framework</h5>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• React 18 with TypeScript</li>
                  <li>• Next.js for fast development</li>
                  <li>• React Router for navigation</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-muted/30 border border-border/50">
                <h5 className="font-medium mb-2">UI Components</h5>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• shadcn/ui component library</li>
                  <li>• Tailwind CSS for styling</li>
                  <li>• Radix UI primitives</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-muted/30 border border-border/50">
                <h5 className="font-medium mb-2">Web3 Integration</h5>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• wagmi for React hooks</li>
                  <li>• viem for Ethereum interactions</li>
                  <li>• WalletConnect v2</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-muted/30 border border-border/50">
                <h5 className="font-medium mb-2">Cryptography</h5>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• snarkjs for proof generation</li>
                  <li>• circomlibjs for hashing</li>
                  <li>• Web Workers for performance</li>
                </ul>
              </div>
            </div>
          </div>

          <CodeBlock
            title="Project Structure"
            language="text"
            code={`src/
├── components/
│   ├── ui/              # shadcn/ui components
│   ├── mixer/           # Deposit/Withdraw components
│   └── layout/          # Page layouts
├── hooks/
│   ├── useDeposit.ts    # Deposit logic
│   ├── useWithdraw.ts   # Withdrawal logic
│   └── useProof.ts      # Proof generation
├── lib/
│   ├── contracts.ts     # Contract ABIs & addresses
│   ├── merkle.ts        # Merkle tree utilities
│   └── crypto.ts        # Cryptographic functions
├── pages/
│   ├── Mixer.tsx        # Main mixer interface
│   └── History.tsx      # Transaction history
└── circuits/
    └── withdraw.wasm    # Compiled circuit`}
          />
        </div>

        {/* Backend/Relayer */}
        <SectionHeader 
          title="Backend & Relayer Services" 
          subtitle="Off-chain infrastructure"
          id="relayer"
        />

        <div className="space-y-4 mb-12">
          <div className="gradient-border rounded-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-lg bg-accent/20 flex items-center justify-center">
                <Server className="w-5 h-5 text-accent" />
              </div>
              <h3 className="text-xl font-semibold">Relayer Network</h3>
            </div>
            <p className="text-muted-foreground mb-4">
              Relayers submit withdrawal transactions on behalf of users, enabling withdrawals 
              without linking gas payments to the recipient address. Key features:
            </p>
            <ul className="space-y-2 text-muted-foreground">
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span><strong className="text-foreground">Privacy Enhancement:</strong> Gas paid by relayer, not recipient</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span><strong className="text-foreground">Fee-based Model:</strong> Relayers charge a small fee deducted from withdrawal</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span><strong className="text-foreground">Decentralized:</strong> Multiple independent relayers can operate</span>
              </li>
            </ul>
          </div>

          <InfoBox variant="info" title="Self-Relaying">
            Users can also submit withdrawals directly without a relayer if they're willing 
            to pay gas from the recipient address. This links the addresses but saves on relayer fees.
          </InfoBox>
        </div>

        {/* Data Flow */}
        <SectionHeader 
          title="Data Flow" 
          subtitle="From deposit to withdrawal"
          id="data-flow"
        />

        <div className="glass-card rounded-xl p-6 mb-8">
          <div className="space-y-6">
            {/* Deposit Flow */}
            <div>
              <h4 className="font-semibold mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-green-500/20 flex items-center justify-center text-xs text-green-500">1</span>
                Deposit Phase
              </h4>
              <div className="flex flex-wrap items-center gap-2 text-sm">
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">User generates secret + nullifier</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">Computes commitment hash</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">Calls deposit(commitment)</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-primary/20 border border-primary/30 text-primary">Commitment added to Merkle tree</span>
              </div>
            </div>

            <div className="h-px bg-border/50" />

            {/* Waiting Period */}
            <div>
              <h4 className="font-semibold mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-yellow-500/20 flex items-center justify-center text-xs text-yellow-500">2</span>
                Anonymity Set Growth
              </h4>
              <p className="text-sm text-muted-foreground">
                The deposit mixes with other deposits in the pool. More deposits = larger anonymity set = stronger privacy.
              </p>
            </div>

            <div className="h-px bg-border/50" />

            {/* Withdrawal Flow */}
            <div>
              <h4 className="font-semibold mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center text-xs text-primary">3</span>
                Withdrawal Phase
              </h4>
              <div className="flex flex-wrap items-center gap-2 text-sm">
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">User enters note + recipient</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">Generates zk-SNARK proof</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-muted/50 border border-border/50">Submits to relayer (optional)</span>
                <ArrowRight className="w-4 h-4 text-muted-foreground" />
                <span className="px-3 py-1.5 rounded-lg bg-primary/20 border border-primary/30 text-primary">Contract verifies & transfers</span>
              </div>
            </div>
          </div>
        </div>

        {/* Security Considerations */}
        <SectionHeader 
          title="Security Considerations" 
          subtitle="Key security measures"
          id="security"
        />

        <div className="space-y-4">
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-muted/20 border border-border/50">
              <h4 className="font-semibold mb-2">On-Chain Security</h4>
              <ul className="text-sm text-muted-foreground space-y-1">
                <li>• Nullifier prevents double-spending</li>
                <li>• Merkle root validation</li>
                <li>• zk-SNARK proof verification</li>
                <li>• Reentrancy protection</li>
              </ul>
            </div>
            <div className="p-4 rounded-xl bg-muted/20 border border-border/50">
              <h4 className="font-semibold mb-2">Off-Chain Security</h4>
              <ul className="text-sm text-muted-foreground space-y-1">
                <li>• Client-side proof generation</li>
                <li>• No secret transmission to servers</li>
                <li>• Local note storage recommended</li>
                <li>• Encrypted backups optional</li>
              </ul>
            </div>
          </div>

          <InfoBox variant="warning" title="Trusted Setup">
            The zk-SNARK circuits require a trusted setup ceremony. The setup parameters must be 
            generated securely with the toxic waste properly discarded. AproxMixer uses a 
            multi-party computation ceremony for this purpose.
          </InfoBox>
        </div>
      </div>
    </DocLayout>
  );
};

export default Architecture;
